package main

import (
	"os"
	"strings"
	"testing"

	"github.com/git-pkgs/brief"
	"github.com/git-pkgs/brief/kb"
)

func TestWriteToolsReadmeOmitsKnowledgeBaseTotals(t *testing.T) {
	var out strings.Builder
	writeToolsReadme(&out, &kb.KnowledgeBase{})

	const introduction = "Language ecosystems and development tools across multiple categories."
	if !strings.Contains(out.String(), introduction) {
		t.Errorf("README output does not contain count-free introduction %q", introduction)
	}
	if strings.Contains(out.String(), "language ecosystems with") {
		t.Errorf("README output contains numeric knowledge-base totals: %q", out.String())
	}
}

func TestToolsReadmeMatchesGeneratedOutput(t *testing.T) {
	knowledgeBase, err := kb.Load(brief.KnowledgeFS)
	if err != nil {
		t.Fatalf("load knowledge base: %v", err)
	}
	var generated strings.Builder
	writeToolsReadme(&generated, knowledgeBase)

	readme, err := os.ReadFile("../../README.md")
	if err != nil {
		t.Fatalf("read README: %v", err)
	}
	readmeText := strings.ReplaceAll(string(readme), "\r\n", "\n")
	const start = "<!-- brief:tools:start (generated by: brief list -readme tools) -->\n"
	const end = "<!-- brief:tools:end -->"
	_, afterStart, ok := strings.Cut(readmeText, start)
	if !ok {
		t.Fatal("README tools start marker is missing")
	}
	section, _, ok := strings.Cut(afterStart, end)
	if !ok {
		t.Fatal("README tools end marker is missing")
	}
	if section != generated.String() {
		t.Error("README tools block differs from `brief list -readme tools` output")
	}
}
